DROP TABLE IF EXISTS Commands;
DROP TABLE IF EXISTS Sensors;
DROP TABLE IF EXISTS Plant;
DROP TABLE IF EXISTS Pot;
DROP TABLE IF EXISTS Pot_Type;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS rules;